### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/javascript#10]
- [x] `eslint-config-bitcrowd-react` should be updated to version `12.0.0` and use `eslint-config-airbnb@12.0.0`
- [x] `eslint-config-bitcrowd-base` should be updated to version `8.0.0` and use `eslint-config-airbnb-base@8.0.0`
- [x] `eslint-config-bitcrowd-angular` should be updated to version `8.0.0` and use the new `eslint-config-bitcrowd-base@8.0.0`

**Comment by weiland** [comment]
I updated the npm packages.
