### ISSUE TITLE
Directly use Airbnb's ESlint config

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/javascript#16]
The only change from Airbnb ESlint config we've made in the bitcrowd packages was to not require `comma-dangle`. However, we cannot update the packages as quickly as Airbnb so the configs are lagging behind.

Therefore I would suggest to update the guide to instead use the Airbnb configs directly and just propose to add the comma-dangle override in the local `.eslintrc` (update `templates/.eslintrc.json`). Plus: Remove the package sources.

**Comment by pmeinhardt** [comment]
I'll have to finish the [PR](https://github.com/bitcrowd/javascript/pull/17) a little later, but basically it'll add different templates rather than packages and installation instructions/links to the relevant resources.

**Comment by planktonic** [comment]
Ah, I got this notification after the initial request for review — you can probably ignore my review comment!

**Comment by pmeinhardt** [comment]
Solved in #17
